### PR TITLE
#11 - Transforming quadratic systems into matrix form

### LINKED ISSUE #11: Transforming quadratic systems into matrix form

### PR DESCRIPTION
**Pull request by schillic**
Closes #11.

This code is quite ugly, but I did not find a clean way to implement it. My problem was that the input terms contain all variables:

```julia
julia> using DynamicPolynomials

julia> @polyvar x y
(x, y)

julia> dx = x + y^2
y² + x

julia> t = dx[1]
y²

julia> t.x.vars
2-element Vector{PolyVar{true}}:
 x
 y
```

Here is an example of the new function:

```julia
julia> using CarlemanLinearization, DynamicPolynomials

julia> @polyvar x y
(x, y)

julia> dx = x + y^2
y² + x

julia> dy = x - y - 2.2 * x * y + x^2
x² - 2.2xy + x - y

julia> F1, F2 = quadratic_matrix_form([(x, dx), (y, dy)]);

julia> F1
2×2 Matrix{Float64}:
 1.0   0.0
 1.0  -1.0

julia> F2
2×4 Matrix{Float64}:
 0.0   0.0  0.0  1.0
 1.0  -2.2  0.0  0.0
```

### CODE REVIEW

**Comment by mforets** [comment]
> the input terms contain all variables

This may be a use case for an API function called [`effective_variables`](https://juliaalgebra.github.io/MultivariatePolynomials.jl/stable/types/#MultivariatePolynomials.effective_variables):

```julia
julia> [@show(m, effective_variables(m)) for m in monomials(dx)];
m = y²
effective_variables(m) = PolyVar{true}[y]
m = x
effective_variables(m) = PolyVar{true}[x]
```

**Review by mforets — COMMENTED** [review]
> This code is quite ugly, but I did not find a clean way to implement it.

It may be possible to use more API functions to make it more compact, but other than that LGTM.

Concerning the interface, it's a matter of taste but I would suggest to define:

```julia
F1, F2 = quadratic_matrix_form(f, vars);
```
where `f = [dx, dy]` and `vars = @polyvar ...` in the example. The `vars` part is important because we can't rely on variables being "ordered" as they were defined using the `@polyvar` macro.

**Comment by schillic** [comment]
The new code requires `MultivariatePolynomials`, right? So should we put it in a `@require` block?

**Comment by mforets** [comment]
Revised example after discussion:

```julia
using CarlemanLinearization, DynamicPolynomials
using CarlemanLinearization: quadratic_matrix_form

# get system in matrix form
vars = @polyvar x y
dx = 3x + y^2
dy = x - y - 2.2 * x * y + x^2
f = [dx, dy]
F1, F2 = quadratic_matrix_form(f, vars)

julia> F1
F22×2 Matrix{Float64}:
 3.0   0.0
 1.0  -1.0

julia> F2
2×4 Matrix{Float64}:
 0.0   0.0  0.0  1.0
 1.0  -2.2  0.0  0.0
```

**Comment by mforets** [comment]
> The new code requires MultivariatePolynomials, right? So should we put it in a @require block?

True, it should be put in such block. I was thinking whether to add it as a firm dependency, since there exist several functions that make use of such API in this repo.

**Comment by schillic** [comment]
I added the block now. We can change it later.

**Review by mforets — APPROVED** [review]

**Pull request merged**
